[workspace]
resolver = "3"
members = ["crates/winmakase", "crates/winmakase-keymap", "crates/winmakase-theme"]

[workspace.package]
version = "0.1.9"
edition = "2024"
license = "MIT"
repository = "https://github.com/railapex/winmakase"
authors = ["Chris Hynes"]

[profile.release]
strip = true
lto = "thin"
