use winmakase_keymap::{AppWindowRule, WindowRuleState, render_glazewm_config};

const BASE: &str = r#"# machine facts stay in the base
workspaces:
  - name: '1'
  - name: '2'
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
"#;

fn app(
    name: &str,
    process: &str,
    class: Option<&str>,
    title: Option<&str>,
    workspace: Option<&str>,
    state: WindowRuleState,
) -> AppWindowRule {
    AppWindowRule {
        name: name.into(),
        process: process.into(),
        class: class.map(str::to_string),
        title: title.map(str::to_string),
        workspace: workspace.map(str::to_string),
        state,
    }
}

#[test]
fn deterministic_rules_match_the_golden() {
    let apps = vec![
        app(
            "browser",
            "chrome",
            None,
            None,
            Some("2"),
            WindowRuleState::Tiling,
        ),
        app(
            "preferences",
            "Acme",
            Some("AcmeDialog"),
            Some("Preferences"),
            None,
            WindowRuleState::Floating,
        ),
        app(
            "browser-pip",
            "chrome",
            Some("Chrome_WidgetWin_1"),
            Some("Picture in picture"),
            None,
            WindowRuleState::Ignored,
        ),
    ];
    let rendered = render_glazewm_config(BASE, &[], &apps).unwrap();
    assert_eq!(rendered, include_str!("golden/glazewm-app-rules.yaml"));

    let parsed: serde_yaml_ng::Value = serde_yaml_ng::from_str(&rendered).unwrap();
    assert!(parsed.get("window_rules").unwrap().is_sequence());
}

#[test]
fn no_apps_preserve_the_w0_base_bytes() {
    let rendered = render_glazewm_config(BASE, &[], &[]).unwrap();
    assert_eq!(
        rendered,
        concat!(
            "# Generated by `winmakase keymap render --base`; edit the base/keymap sources, not this file.\n",
            "# machine facts stay in the base\n",
            "workspaces:\n",
            "  - name: '1'\n",
            "  - name: '2'\n",
            "window_rules:\n",
            "  - commands: ['ignore']\n",
            "    match:\n",
            "      - window_process: { equals: 'zebar' }\n\n",
            "keybindings:\n",
        )
    );
}

#[test]
fn workspace_and_policy_conflicts_fail_loud() {
    let unknown_workspace = app(
        "browser",
        "chrome",
        None,
        None,
        Some("9"),
        WindowRuleState::Tiling,
    );
    let error = render_glazewm_config(BASE, &[], &[unknown_workspace]).unwrap_err();
    assert!(error.contains("does not declare"), "{error}");

    let broad = app(
        "browser",
        "chrome",
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let dialog = app(
        "browser-dialog",
        "chrome",
        Some("Chrome_WidgetWin_1"),
        None,
        None,
        WindowRuleState::Floating,
    );
    let error = render_glazewm_config(BASE, &[], &[broad, dialog]).unwrap_err();
    assert!(error.contains("contradictory"), "{error}");
}

#[test]
fn narrow_ignore_is_the_only_contradictory_overlap_with_defined_order() {
    let broad = app(
        "browser",
        "chrome",
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let popup = app(
        "browser-popup",
        "chrome",
        Some("Chrome_WidgetWin_1"),
        Some("Popup"),
        None,
        WindowRuleState::Ignored,
    );
    let rendered = render_glazewm_config(BASE, &[], &[broad, popup]).unwrap();
    let ignored = rendered.find("equals: Popup").unwrap();
    let broad = rendered.rfind("equals: chrome").unwrap();
    assert!(ignored < broad, "{rendered}");
}

#[test]
fn base_and_config_cannot_own_the_same_app_policy() {
    let base = r#"
workspaces:
  - name: '2'
window_rules:
  - commands: ['set-floating']
    match:
      - window_process: { equals: 'chrome' }
"#;
    let browser = app(
        "browser",
        "chrome",
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let error = render_glazewm_config(base, &[], &[browser]).unwrap_err();
    assert!(error.contains("keep that policy in one source"), "{error}");
}

#[test]
fn malformed_or_ambiguous_base_fails_loud() {
    for (base, expected) in [
        ("workspaces: [", "not valid YAML"),
        ("window_rules: nope\n", "window_rules must be a list"),
        ("window_rules: []\nwindow_rules: []\n", "not valid YAML"),
        ("workspaces:\n  - bind_to_monitor: 0\n", "string name"),
    ] {
        let error = render_glazewm_config(base, &[], &[]).unwrap_err();
        assert!(
            error.contains(expected),
            "expected {expected:?}, got {error:?}"
        );
    }
}
