use winmakase_keymap::{AppWindowRule, WindowRuleState, render_glazewm_config};

const BASE: &str = r#"# machine facts stay in the base
workspaces:
  - name: '1'
  - name: '2'
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'zebar' }
"#;

fn app(
    name: &str,
    process: &str,
    class: Option<&str>,
    title: Option<&str>,
    app_id: Option<&str>,
    workspace: Option<&str>,
    state: WindowRuleState,
) -> AppWindowRule {
    AppWindowRule {
        name: name.into(),
        process: process.into(),
        class: class.map(str::to_string),
        title: title.map(str::to_string),
        app_id: app_id.map(str::to_string),
        workspace: workspace.map(str::to_string),
        has_owner: None,
        resizable: None,
        state,
    }
}

#[test]
fn deterministic_rules_match_the_golden() {
    let apps = vec![
        app(
            "browser",
            "chrome",
            None,
            None,
            Some("Chrome"),
            Some("2"),
            WindowRuleState::Tiling,
        ),
        app(
            "preferences",
            "Acme",
            Some("AcmeDialog"),
            Some("Preferences"),
            None,
            None,
            WindowRuleState::Floating,
        ),
        app(
            "browser-pip",
            "chrome",
            Some("Chrome_WidgetWin_1"),
            Some("Picture in picture"),
            None,
            None,
            WindowRuleState::Ignored,
        ),
    ];
    let rendered = render_glazewm_config(BASE, &[], &apps).unwrap();
    assert_eq!(rendered, include_str!("golden/glazewm-app-rules.yaml"));

    let parsed: serde_yaml_ng::Value = serde_yaml_ng::from_str(&rendered).unwrap();
    assert!(parsed.get("window_rules").unwrap().is_sequence());
}

#[test]
fn no_apps_preserve_the_w0_base_bytes() {
    let rendered = render_glazewm_config(BASE, &[], &[]).unwrap();
    assert_eq!(
        rendered,
        concat!(
            "# Generated by `winmakase keymap render --base`; edit the base/keymap sources, not this file.\n",
            "# machine facts stay in the base\n",
            "workspaces:\n",
            "  - name: '1'\n",
            "  - name: '2'\n",
            "window_rules:\n",
            "  - commands: ['ignore']\n",
            "    match:\n",
            "      - window_process: { equals: 'zebar' }\n\n",
            "keybindings:\n",
        )
    );
}

#[test]
fn preserve_homes_move_only_main_windows() {
    let browser = app(
        "browser",
        "chrome",
        None,
        None,
        Some("Chrome"),
        Some("2"),
        WindowRuleState::Preserve,
    );
    let rendered = render_glazewm_config(BASE, &[], &[browser]).unwrap();
    assert!(rendered.contains("move --workspace 2"));
    assert!(rendered.contains("window_has_owner: false"));
    assert!(rendered.contains("window_is_resizable: true"));
    assert!(!rendered.contains("set-tiling"));
    assert!(!rendered.contains("set-floating"));
}

#[test]
fn launch_identity_without_manage_policy_emits_no_rule() {
    let browser = app(
        "browser",
        "chrome",
        None,
        None,
        Some("Chrome"),
        None,
        WindowRuleState::Preserve,
    );
    let rendered = render_glazewm_config(BASE, &[], &[browser]).unwrap();
    assert_eq!(
        rendered,
        concat!(
            "# Generated by `winmakase keymap render --base`; edit the base/keymap sources, not this file.\n",
            "# machine facts stay in the base\n",
            "workspaces:\n",
            "  - name: '1'\n",
            "  - name: '2'\n",
            "window_rules:\n",
            "  - commands: ['ignore']\n",
            "    match:\n",
            "      - window_process: { equals: 'zebar' }\n\n",
            "keybindings:\n",
        )
    );
}

#[test]
fn boolean_disjoint_dialog_policy_can_share_a_process() {
    let main = app(
        "main",
        "Fixture",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Preserve,
    );
    let mut dialog = app(
        "dialog",
        "Fixture",
        None,
        None,
        None,
        None,
        WindowRuleState::Floating,
    );
    dialog.has_owner = Some(true);
    let rendered = render_glazewm_config(BASE, &[], &[main, dialog]).unwrap();
    assert!(rendered.contains("window_has_owner: true"));
    assert!(rendered.contains("window_has_owner: false"));
}

#[test]
fn broad_dialog_policy_still_conflicts_with_a_main_home() {
    let main = app(
        "main",
        "Fixture",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Preserve,
    );
    let dialog = app(
        "dialog",
        "Fixture",
        None,
        None,
        None,
        None,
        WindowRuleState::Floating,
    );
    let error = render_glazewm_config(BASE, &[], &[main, dialog]).unwrap_err();
    assert!(error.contains("contradictory"), "{error}");
}

#[test]
fn native_fact_only_ignore_cannot_suppress_an_entire_main_rule() {
    let main = app(
        "main",
        "Fixture",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Preserve,
    );
    let mut ignored = app(
        "ignored",
        "Fixture",
        None,
        None,
        None,
        None,
        WindowRuleState::Ignored,
    );
    ignored.has_owner = Some(false);
    let error = render_glazewm_config(BASE, &[], &[main, ignored]).unwrap_err();
    assert!(error.contains("contradictory"), "{error}");
}

#[test]
fn workspace_and_policy_conflicts_fail_loud() {
    let unknown_workspace = app(
        "browser",
        "chrome",
        None,
        None,
        None,
        Some("9"),
        WindowRuleState::Tiling,
    );
    let error = render_glazewm_config(BASE, &[], &[unknown_workspace]).unwrap_err();
    assert!(error.contains("does not declare"), "{error}");

    let broad = app(
        "browser",
        "chrome",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let dialog = app(
        "browser-dialog",
        "chrome",
        Some("Chrome_WidgetWin_1"),
        None,
        None,
        None,
        WindowRuleState::Floating,
    );
    let error = render_glazewm_config(BASE, &[], &[broad, dialog]).unwrap_err();
    assert!(error.contains("contradictory"), "{error}");
}

#[test]
fn narrow_ignore_is_the_only_contradictory_overlap_with_defined_order() {
    let broad = app(
        "browser",
        "chrome",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let popup = app(
        "browser-popup",
        "chrome",
        Some("Chrome_WidgetWin_1"),
        Some("Popup"),
        None,
        None,
        WindowRuleState::Ignored,
    );
    let rendered = render_glazewm_config(BASE, &[], &[broad, popup]).unwrap();
    let ignored = rendered.find("equals: Popup").unwrap();
    let broad = rendered.rfind("equals: chrome").unwrap();
    assert!(ignored < broad, "{rendered}");
}

#[test]
fn base_and_config_cannot_own_the_same_app_policy() {
    let base = r#"
workspaces:
  - name: '2'
window_rules:
  - commands: ['set-floating']
    match:
      - window_process: { equals: 'chrome' }
"#;
    let browser = app(
        "browser",
        "chrome",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let error = render_glazewm_config(base, &[], &[browser]).unwrap_err();
    assert!(error.contains("keep that policy in one source"), "{error}");
}

#[test]
fn non_exact_base_conflicts_do_not_bypass_ownership_validation() {
    let browser = app(
        "browser",
        "chrome",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    for matcher in [
        "window_process: { regex: '^chrome$' }",
        "window_process: { includes: 'chrom' }",
        "window_process: { not_equals: 'firefox' }",
        "window_process: { not_regex: '^firefox$' }",
    ] {
        let base = format!(
            "workspaces:\n  - name: '2'\nwindow_rules:\n  - commands: ['set-floating']\n    match:\n      - {matcher}\n"
        );
        let error = render_glazewm_config(&base, &[], std::slice::from_ref(&browser))
            .expect_err("overlap must not be silently accepted");
        assert!(error.contains("keep that policy in one source"), "{error}");
    }
}

#[test]
fn narrow_regex_ignore_remains_a_decisive_base_exception() {
    let base = r#"
workspaces:
  - name: '2'
window_rules:
  - commands: ['ignore']
    match:
      - window_process: { equals: 'chrome' }
        window_title: { regex: '[Pp]icture.in.[Pp]icture' }
"#;
    let browser = app(
        "browser",
        "chrome",
        None,
        None,
        None,
        Some("2"),
        WindowRuleState::Tiling,
    );
    let rendered = render_glazewm_config(base, &[], &[browser]).unwrap();
    assert!(rendered.find("regex:").unwrap() < rendered.find("move --workspace 2").unwrap());
}

#[test]
fn app_ids_disambiguate_chromium_profiles() {
    let ownerrez = app(
        "ownerrez",
        "chrome",
        None,
        None,
        Some("Chrome"),
        Some("1"),
        WindowRuleState::Tiling,
    );
    let personal = app(
        "personal",
        "chrome",
        None,
        None,
        Some("Chrome.UserData.Profile1"),
        Some("2"),
        WindowRuleState::Tiling,
    );
    let rendered = render_glazewm_config(BASE, &[], &[ownerrez, personal]).unwrap();
    assert!(rendered.contains("equals: Chrome.UserData.Profile1"));
}

#[test]
fn malformed_or_ambiguous_base_fails_loud() {
    for (base, expected) in [
        ("workspaces: [", "not valid YAML"),
        ("window_rules: nope\n", "window_rules must be a list"),
        ("window_rules: []\nwindow_rules: []\n", "not valid YAML"),
        ("workspaces:\n  - bind_to_monitor: 0\n", "string name"),
        (
            "window_rules:\n  - commands: ['ignore']\n    match:\n      - window_process: { starts_with: 'z' }\n",
            "unknown matcher",
        ),
        (
            "window_rules:\n  - commands: ['ignore']\n    match:\n      - window_process: { equals: 'zebar', regex: 'zebar' }\n",
            "exactly one",
        ),
        (
            "window_rules:\n  - commands: ['ignore']\n    match:\n      - window_process: { regex: '' }\n",
            "must not be empty",
        ),
        (
            "window_rules:\n  - commands: ['ignore']\n    match:\n      - window_process: { equals: 'zebar' }\n        window_titel: { equals: 'typo' }\n",
            "unknown match field",
        ),
        (
            "window_rules:\n  - commands: ['ignore']\n    match:\n      - window_has_owner: 'false'\n",
            "must be a boolean",
        ),
    ] {
        let error = render_glazewm_config(base, &[], &[]).unwrap_err();
        assert!(
            error.contains(expected),
            "expected {expected:?}, got {error:?}"
        );
    }
}
